### ISSUE TITLE
缺少聲明gtest/gtest.h文件，可以補上嗎謝謝

### ISSUE THREAD

**Issue by 16903491** [fuqiuluo/Hakutaku#1]
缺少聲明gtest/gtest.h文件，可以補上嗎謝謝

**Comment by fuqiuluo** [comment]
自己从[gtest](https://github.com/google/googletest)下载一份，测试用的，正式发布没有用。

**Comment by 16903491** [comment]
我是看你源代码里都有引用，但是目录里却没有这个，所以想请你提供一下

**Comment by fuqiuluo** [comment]
也行，等一下我提交一份

**Comment by fuqiuluo** [comment]
有点大，你自己下载吧...(

**Comment by 16903491** [comment]
好的，非常感谢，可以加个QQ好友偶尔请教下吗？我7867056

**Comment by fuqiuluo** [comment]
有问题发issue就可以了。

**Comment by 16903491** [comment]
我想写一个内存插件，给按键精灵调用
实现的功能有：
1，读内存地址
2，写内存地址
3，读指针+偏移
4，写指针+偏移
5，搜特征码
自己写了前4个，但是速度不是很快，而且不能给64位使用，所以想请教下你，我看你这个代码写的很精简

**Comment by fuqiuluo** [comment]
嗯
