### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by enenH** [fuqiuluo/Hakutaku#14]
https://github.com/fuqiuluo/Hakutaku/blob/699e72e5555c6b613dcd656d907d7977c146cffc/core/Hakutaku.hpp#L608
这里应该是getuid 把写手滑了
https://github.com/fuqiuluo/Hakutaku/blob/699e72e5555c6b613dcd656d907d7977c146cffc/core/Hakutaku.hpp#L877
天机处理器莫的 /dev/kgsl-3d0，有 /dev/mali0

**Comment by fuqiuluo** [comment]
![image](https://github.com/fuqiuluo/Hakutaku/assets/61898844/ed6210c8-9cc1-4a48-96c3-5c41628950ad)
这个是重写之后的V内存界定

**Comment by fuqiuluo** [comment]
目前无法解决的是如何轻松的实现类似于GG修改器的模糊搜索...
