### ISSUE TITLE
How to build on Android？

### ISSUE THREAD

**Issue by ZYPyDoki** [fuqiuluo/Hakutaku#21]
你好开发者，请问我该怎么在android手机平台编译使用Hakutaku呢？

**Comment by fuqiuluo** [comment]
Clion设置安卓ndk工具链（可以从google的网站里面下载），然后配置好各类参数，即可构建Hakutaku

**Comment by ZYPyDoki** [comment]
> Clion设置安卓ndk工具链（可以从google的网站里面下载），然后配置好各类参数，即可构建Hakutaku


问题已解决
方法：利用了termux，安装了git，cmake，然后改了改两三个.h头文件的添加include，就可以成功cmake编译了。

体验感受：感觉挺好用的，支持，感觉功能很强大，就是c++的各种::还得细细琢磨研究，利用termux除了编译有点慢，别的都还行，感谢大佬解答
