### ISSUE TITLE
Can you give example how to write all found value after Searching & Filter value??

### ISSUE THREAD

**Issue by MikaCybertron** [fuqiuluo/Hakutaku#7]
Can you give example how to write all found value after Searching & Filter value??

for example after searching value and filter it, then write value 999999 to all found value

![image](https://user-images.githubusercontent.com/45533977/236013718-ae7d68a1-66ff-41f4-9597-4accf52b5c9f.png)

**Comment by fuqiuluo** [comment]
You can look at the following code：
```c++
std::string packageName = "com.example.app";
pid_t pid = Hakutaku::getPid(packageName);
Hakutaku::Process process = Hakutaku::openProcess(pid);
// based value search
Hakutaku::MemorySearcher searcher = process.getSearcher();
int ret = searcher.searchNumber("1D");
// ...
ret = searcher.filterNumber("4D");
std::for_each(searcher.getResult().begin(), searcher.getResult().end(), [&](const std::set<Pointer> &ptrSet) {
    printf("==========> Group[%zu]\n", ptrSet.size());
    std::for_each(ptrSet.begin(), ptrSet.end(), [&](const auto &ptr) {
        int write_data = 1234;
        process.write(ptr, &write_data, sizeof(int));
        printf("writeTo: 0x%04lx\n", ptr);
     });
     printf("\n");
});
```
The *ptrSet* actually refers to all the pointers to a set of data that is federated.

**Comment by fuqiuluo** [comment]
Writing code with Clion or VSCode can result in significant code completion. #

**Comment by MikaCybertron** [comment]
thanks, i will test it and give the feedback soon after i'm done with my current projects.
