### ISSUE TITLE
When i try to add Hakutaku.hpp to my template then i got a lot of error

### ISSUE THREAD

**Issue by MikaCybertron** [fuqiuluo/Hakutaku#8]
when i try to add the core source to my template then i got a lot of error, here

![image](https://user-images.githubusercontent.com/45533977/236374155-cb3367fa-4287-4939-b20b-8d1ab2a6883a.png)

maybe the issue was my CMakeLists.txt since i'm not good with it, if the error was there then could you fix my CMakeLists.txt??
[CMakeLists.txt](https://github.com/fuqiuluo/Hakutaku/files/11403162/CMakeLists.txt)

**Comment by fuqiuluo** [comment]
Please check your C++/C compiler version, because I found that your compiler doesn't even support the STL container std::set.

**Comment by fuqiuluo** [comment]
This problem turns out to be caused by your compiler or IDE not supporting higher version C++ writing, such as STL containers or lambda writing.
