### ISSUE TITLE
Collaboration Invitation 

### ISSUE THREAD

**Issue by KuhakuPixel** [fuqiuluo/Hakutaku#9]
Hello, I saw you are creating a mem scanner/editor for android
I too have created one [here](https://github.com/KuhakuPixel/ACEthegame)

which already have a cli program that can be run via `adb shell`
to scan and edit memory

there are many features still missing though such as 
apk gui, undo scan, scan for 64 bit decimal and etc
So I was hoping we can combine our skills to build apk like Game Guardian :D

**Comment by fuqiuluo** [comment]
I'm planning to build an apk similar to Game Guardian, but without the windows UI.

**Comment by fuqiuluo** [comment]
I'd love to join you. I'm getting familiar with the structure of your project. How many people are there in your development?

**Comment by KuhakuPixel** [comment]
Currently Its only me :D, if you have any question about the structure and etc, feel free to ask me on discord :+1:
